In [6]:
from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()

df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
df["target"] = iris_data.target

In [19]:
df.head(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 149 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  149 non-null    float64
 1   sepal width (cm)   149 non-null    float64
 2   petal length (cm)  149 non-null    float64
 3   petal width (cm)   149 non-null    float64
 4   target             149 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 7.0 KB

In [10]:
df.duplicated().sum()

np.int64(1)

In [12]:
df = df.drop_duplicates()

In [14]:
df.corr(numeric_only=True)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
sepal length (cm),1.000000,-0.118129,0.873738,0.820620,0.786971
sepal width (cm),-0.118129,1.000000,-0.426028,-0.362894,-0.422987
petal length (cm),0.873738,-0.426028,1.000000,0.962772,0.949402
petal width (cm),0.820620,-0.362894,0.962772,1.000000,0.956514
target,0.786971,-0.422987,0.949402,0.956514,1.000000

In [16]:
from sklearn.model_selection import train_test_split

x = df.drop(columns="target")
y = df["target"]

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=40, test_size=.20, stratify=y)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

prediction = model.predict(x_test)

In [24]:
print("Score :", model.score(x_test, y_test))

Score : 0.9333333333333333

In [25]:
from sklearn.metrics import accuracy_score

print("accuracy score :", accuracy_score(y_test,prediction))

accuracy score : 0.9333333333333333