In [1]:
import pandas as pd

df = pd.read_csv("/home/abijithpersonal/Documents/Recap_ML/paper_three/Paper3/data/data.csv")

In [4]:
df.head(5)

   id                 location  bedrooms   sq_ft  price_lakhs  age_years
0   1         Kochi - Kakkanad       3.0  1450.0         65.5          2
1   2        Kochi - Edappally       2.0  1100.0         45.0          5
2   3  Trivandrum - Technopark       3.0     NaN         80.0          1
3   4         Kochi - Kakkanad       4.0  2200.0        120.0          0
4   5     Kochi - Palarivattom       NaN   950.0         55.0          8

In [5]:
df.tail(5)

    id              location  bedrooms    sq_ft  price_lakhs  age_years
7    8      Kochi - Kakkanad       3.0   1400.0          NaN          4
8    9      Kochi - Infopark       2.0  50000.0         45.0          2
9   10   Trivandrum - Pattom       3.0   1350.0         70.0          6
10  11  Calicut - Beach Road       NaN   1600.0         95.0          4
11  12     Kochi - Edappally       2.0   1050.0         42.0          7

In [6]:
df.shape

(12, 6)

In [7]:
df.dtypes

id               int64
location           str
bedrooms       float64
sq_ft          float64
price_lakhs    float64
age_years        int64
dtype: object

In [8]:
df.columns

Index(['id', 'location', 'bedrooms', 'sq_ft', 'price_lakhs', 'age_years'], dtype='str')